# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Basic-example" data-toc-modified-id="Basic-example-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Basic example</a></div><div class="lev1 toc-item"><a href="#Array-creation" data-toc-modified-id="Array-creation-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Array creation</a></div><div class="lev1 toc-item"><a href="#Basic-operations" data-toc-modified-id="Basic-operations-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Basic operations</a></div><div class="lev1 toc-item"><a href="#Universal-functions" data-toc-modified-id="Universal-functions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Universal functions</a></div><div class="lev1 toc-item"><a href="#Indexing,-slicing-and-iterating" data-toc-modified-id="Indexing,-slicing-and-iterating-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Indexing, slicing and iterating</a></div><div class="lev1 toc-item"><a href="#Shape-manipulation" data-toc-modified-id="Shape-manipulation-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Shape manipulation</a></div><div class="lev1 toc-item"><a href="#Stacking-arrays" data-toc-modified-id="Stacking-arrays-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Stacking arrays</a></div><div class="lev1 toc-item"><a href="#Splitting-array" data-toc-modified-id="Splitting-array-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Splitting array</a></div><div class="lev1 toc-item"><a href="#View-or-Shallow-Copy" data-toc-modified-id="View-or-Shallow-Copy-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>View or Shallow Copy</a></div><div class="lev1 toc-item"><a href="#Less-basic" data-toc-modified-id="Less-basic-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Less basic</a></div><div class="lev1 toc-item"><a href="#Indexing-tricks" data-toc-modified-id="Indexing-tricks-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Indexing tricks</a></div>

# Basic example

In [2]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [12]:
b = np.array([6,7,8])
b

array([6, 7, 8])

# Array creation

In [14]:
int_arr = np.array([2,3,4])
print(int_arr.dtype)
float_arr = np.array([2.3,5.6,3.4])
print(float_arr.dtype)

int64
float64


In [15]:
np.array([(1.4,4,3), (1,4,5)])

array([[ 1.4,  4. ,  3. ],
       [ 1. ,  4. ,  5. ]])

In [16]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

Use `linspace` when wanting floating point steps, instead of specifying the floating size directly in `arange`.

In [18]:
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

# Basic operations

In [20]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [21]:
c = a - b
c

array([20, 29, 38, 47])

In [22]:
b ** 2

array([0, 1, 4, 9])

`*` operates elementwise in this context, instead of performing dot-product.

In [23]:
a = np.array([1,2,3])
b = np.array([2,2,2])
a * b

array([2, 4, 6])

Many unary operations are implemented as direct methods.

In [25]:
r = np.random.random((2,3))
r

array([[ 0.83162123,  0.75124574,  0.05019661],
       [ 0.6880916 ,  0.58456307,  0.93105775]])

In [27]:
r.sum()

3.8367759985691157

In [28]:
r.min()

0.050196611761627818

In [29]:
r.max()

0.93105774756480475

# Universal functions

Particular 'universal' functions allowing elementwise operation on array, producing array as output.

In [31]:
B = np.arange(3)
B

array([0, 1, 2])

In [32]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [33]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [34]:
C = np.array([2,-1,4])
print(np.add(B, C))
print(B+C)

[2 0 6]
[2 0 6]


# Indexing, slicing and iterating

In [36]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [37]:
a[2:5]

array([ 8, 27, 64])

In [39]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [40]:
b[1:3,1:3]

array([[11, 12],
       [21, 22]])

# Shape manipulation

In [41]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 3.,  0.,  9.,  3.],
       [ 6.,  9.,  1.,  7.],
       [ 5.,  5.,  3.,  0.]])

In [42]:
a.shape

(3, 4)

In [43]:
a.ravel()  # Flatten!

array([ 3.,  0.,  9.,  3.,  6.,  9.,  1.,  7.,  5.,  5.,  3.,  0.])

In [44]:
a.reshape(6,2)

array([[ 3.,  0.],
       [ 9.,  3.],
       [ 6.,  9.],
       [ 1.,  7.],
       [ 5.,  5.],
       [ 3.,  0.]])

In [47]:
a.reshape(6,2).T

array([[ 3.,  9.,  6.,  1.,  5.,  3.],
       [ 0.,  3.,  9.,  7.,  5.,  0.]])

In [50]:
a.reshape(3,-1)  # Calculate nbr cols automatically

array([[ 3.,  0.,  9.,  3.],
       [ 6.,  9.,  1.,  7.],
       [ 5.,  5.,  3.,  0.]])

# Stacking arrays

In [ ]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

# Splitting array

In [56]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a, 3))
print(np.vsplit(a, 2))

[[ 7.  2.  3.  7.  8.  3.  3.  2.  0.  0.  7.  7.]
 [ 3.  6.  2.  0.  8.  4.  1.  5.  5.  9.  0.  0.]]
[array([[ 7.,  2.,  3.,  7.],
       [ 3.,  6.,  2.,  0.]]), array([[ 8.,  3.,  3.,  2.],
       [ 8.,  4.,  1.,  5.]]), array([[ 0.,  0.,  7.,  7.],
       [ 5.,  9.,  0.,  0.]])]
[array([[ 7.,  2.,  3.,  7.,  8.,  3.,  3.,  2.,  0.,  0.,  7.,  7.]]), array([[ 3.,  6.,  2.,  0.,  8.,  4.,  1.,  5.,  5.,  9.,  0.,  0.]])]


# View or Shallow Copy

Can create reference to same object with `view`!

Slicing returns view.

In [60]:
c = a.view()
c[0,4] = 1234
print(a)
copy = a.copy()
copy[0,3] = 1000000
print(a)
print(copy)

[[  7.00000000e+00   2.00000000e+00   3.00000000e+00   7.00000000e+00
    1.23400000e+03   3.00000000e+00   3.00000000e+00   2.00000000e+00
    0.00000000e+00   0.00000000e+00   7.00000000e+00   7.00000000e+00]
 [  3.00000000e+00   6.00000000e+00   2.00000000e+00   0.00000000e+00
    8.00000000e+00   4.00000000e+00   1.00000000e+00   5.00000000e+00
    5.00000000e+00   9.00000000e+00   0.00000000e+00   0.00000000e+00]]
[[  7.00000000e+00   2.00000000e+00   3.00000000e+00   7.00000000e+00
    1.23400000e+03   3.00000000e+00   3.00000000e+00   2.00000000e+00
    0.00000000e+00   0.00000000e+00   7.00000000e+00   7.00000000e+00]
 [  3.00000000e+00   6.00000000e+00   2.00000000e+00   0.00000000e+00
    8.00000000e+00   4.00000000e+00   1.00000000e+00   5.00000000e+00
    5.00000000e+00   9.00000000e+00   0.00000000e+00   0.00000000e+00]]
[[  7.00000000e+00   2.00000000e+00   3.00000000e+00   1.00000000e+06
    1.23400000e+03   3.00000000e+00   3.00000000e+00   2.00000000e+00
    0.00000000

# Less basic

Broadcasting: Allow universal functions to deal in meaningful way for inputs not having the exact same shape.

Rules:

* If input arrays don't have same number of dimensions, 1 will be prepended to smaller arrays until same number of dimensions.
* Arrays with size of 1 act as they had size of array with largest shape along that dimension.

# Indexing tricks

In [61]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [63]:
i = np.array([1,1,3,8,5])
a[i]

array([ 1,  1,  9, 64, 25])

In [64]:
j = np.array([[3,4],[9,7]])
a[j]

array([[ 9, 16],
       [81, 49]])

Contrast vector!

In [65]:
a[[True,True,True,False,False,False,True,True,True,False,False,False]]

array([ 0,  1,  4, 36, 49, 64])